"""minacalc_estimator.py — Role-based MinaCalc MSD dan Reform estimator.

Architecture:
    .osu → MinaCalc MSD@1.0x → 4 role scores → per-role dan lookup
         → structural feature modulation → composite dan → result dict

Roles:
    jack    = max(jackspeed, chordjack)
    tech    = technical
    speed   = max(stream, jumpstream)
    stamina = 0.7 * stamina + 0.3 * handstream  (blended — must match calibration script)

Structural integration (3 tiers):
    A — confidence-only: features modulate confidence, never shift dan
    B — microshift: features allow ±0.5 dan adjustment for well-supported signals
    C — explanation: features only appear in the explanation text

Requires:
    - tools/bin/minacalc_cli.exe (built with cargo)
    - config/role_scales.json (generated by _build_role_scales.py)
"""

import json
import math
import os
import statistics
import sys
from collections import Counter

from minacalc_bridge import calc as minacalc_calc

if getattr(sys, "frozen", False):
    _SCALES_PATH = os.path.join(sys._MEIPASS, "config", "role_scales.json")
else:
    _ROOT = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", ".."))
    _SCALES_PATH = os.path.join(_ROOT, "config", "role_scales.json")

_ROLES = ["jack", "speed", "tech", "stamina"]

_DAN_ORDER = [
    "1st", "2nd", "3rd", "4th", "5th",
    "6th", "7th", "8th", "9th", "10th",
    "Alpha", "Beta", "Gamma", "Delta", "Epsilon",
    "Zeta", "Eta", "Theta", "Iota", "Kappa",
]

_DAN_LABELS = {
    "1st": "1st Dan", "2nd": "2nd Dan", "3rd": "3rd Dan",
    "4th": "4th Dan", "5th": "5th Dan", "6th": "6th Dan",
    "7th": "7th Dan", "8th": "8th Dan", "9th": "9th Dan",
    "10th": "10th Dan", "Alpha": "Alpha", "Beta": "Beta",
    "Gamma": "Gamma", "Delta": "Delta", "Epsilon": "Epsilon",
    "Zeta": "Zeta", "Eta": "Eta", "Theta": "Theta",
    "Iota": "Iota", "Kappa": "Kappa",
}

_scales: dict | None = None


def _load_scales() -> dict | None:
    global _scales
    if _scales is not None:
        return _scales
    if not os.path.isfile(_SCALES_PATH):
        return None
    try:
        with open(_SCALES_PATH, encoding="utf-8") as f:
            _scales = json.load(f)
        return _scales
    except (json.JSONDecodeError, OSError):
        return None


# ── Role score extraction ─────────────────────────────────────────────────────

_DAN_SHORT = {
    "1st": "1", "2nd": "2", "3rd": "3", "4th": "4", "5th": "5",
    "6th": "6", "7th": "7", "8th": "8", "9th": "9", "10th": "10",
    "Alpha": "α", "Beta": "β", "Gamma": "γ", "Delta": "δ", "Epsilon": "ε",
    "Zeta": "ζ", "Eta": "η", "Theta": "θ", "Iota": "ι", "Kappa": "κ",
}


def _role_scores(scores: dict) -> dict[str, float]:
    """Compute the 4 role scores from raw MinaCalc skillsets."""
    stam = scores.get("stamina", 0.0)
    hs   = scores.get("handstream", 0.0)
    return {
        "jack":    max(scores.get("jackspeed", 0.0), scores.get("chordjack", 0.0)),
        "tech":    scores.get("technical", 0.0),
        "speed":   max(scores.get("stream", 0.0), scores.get("jumpstream", 0.0)),
        "stamina": 0.7 * stam + 0.3 * hs,
    }


# ── Structural feature extraction (graceful fallback) ─────────────────────────

def _extract_structural(osu_path: str) -> dict:
    """Parse the .osu and extract structural features. Returns {} on failure."""
    try:
        from parser import parsear_osu_v2
        from feature_extractor import extract_features
        parsed = parsear_osu_v2(osu_path, enforce_mode_mania=True, enforce_keycount=4)
        if parsed.get("rejected"):
            return {}
        return extract_features(parsed)
    except Exception:
        return {}


# ── Band-based per-role dan lookup (Fase 3) ───────────────────────────────────

def _band_position(value: float, lower: float, center: float, upper: float) -> float:
    """Position within band: 0.0 at lower, 0.5 at center, 1.0 at upper."""
    if value <= center:
        half = max(center - lower, 0.001)
        pos = 0.5 * (value - lower) / half
    else:
        half = max(upper - center, 0.001)
        pos = 0.5 + 0.5 * (value - center) / half
    return max(0.0, min(1.0, pos))


def _center_confidence(value: float, lower: float, center: float, upper: float) -> float:
    """Confidence based on proximity to center within the band. 1.0 at center, 0.0 at edges."""
    half_width = max((upper - lower) / 2, 0.001)
    dist = abs(value - center)
    return max(0.0, min(1.0, 1.0 - dist / half_width))


def _anchor_quality(sample_count: int, risk_flag: str, dispersion: float) -> float:
    """Quality multiplier based on anchor reliability."""
    if sample_count < 2 or risk_flag == "weak":
        return 0.65
    if risk_flag == "dispersed" or dispersion > 3.0:
        return 0.80
    return 1.0


def _lookup_role_dan(value: float, role_thresholds: dict) -> tuple[str, float, float]:
    """Return (dan, position, confidence) using interval-based lookup.

    Uses [lower, upper] bands with center as primary anchor.
    Confidence is modulated by proximity to center and anchor quality.
    Overlap zones reduce confidence to signal ambiguity.
    """
    # Build ordered list of bands
    bands = []
    for d in _DAN_ORDER:
        if d in role_thresholds:
            t = role_thresholds[d]
            bands.append((
                d,
                t["lower"], t["center"], t["upper"],
                t.get("sample_count", 1),
                t.get("risk_flag", "weak"),
                t.get("dispersion", 0.0),
            ))

    if not bands:
        return "1st", 0.5, 0.0

    # Find which band(s) contain the value
    containing = [(i, b) for i, b in enumerate(bands) if b[1] <= value <= b[3]]

    if len(containing) == 1:
        # Clean hit in exactly one band
        _i, (dan, lower, center, upper, n, flag, disp) = containing[0]
        position = _band_position(value, lower, center, upper)
        base_conf = _center_confidence(value, lower, center, upper)
        quality = _anchor_quality(n, flag, disp)
        return dan, round(position, 3), round(base_conf * quality, 3)

    elif len(containing) > 1:
        # Overlap zone — pick closest center, reduce confidence
        best = min(containing, key=lambda x: abs(value - x[1][2]))
        _i, (dan, lower, center, upper, n, flag, disp) = best
        position = _band_position(value, lower, center, upper)
        base_conf = _center_confidence(value, lower, center, upper)
        quality = _anchor_quality(n, flag, disp)
        overlap_penalty = 0.70
        return dan, round(position, 3), round(base_conf * quality * overlap_penalty, 3)

    else:
        # Falls outside all bands — nearest center fallback
        best_idx = min(range(len(bands)), key=lambda i: abs(value - bands[i][2]))
        dan, lower, center, upper, n, flag, disp = bands[best_idx]
        position = _band_position(value, lower, center, upper)
        half_width = max((upper - lower) / 2, 0.001)
        dist = abs(value - center)
        base_conf = max(0.0, 1.0 - dist / half_width) * 0.5
        quality = _anchor_quality(n, flag, disp)
        return dan, round(position, 3), round(base_conf * quality, 3)


def _sublevel(position: float) -> str:
    if position < 0.20:
        return "Low"
    elif position < 0.40:
        return "Mid-Low"
    elif position < 0.60:
        return "Mid"
    elif position < 0.80:
        return "Mid-High"
    return "High"


def _dan_index(dan: str) -> int:
    try:
        return _DAN_ORDER.index(dan)
    except ValueError:
        return 0


# ── Primary role detection with structural bias (Fase 4+5) ────────────────────

_STRUCTURAL_ROLE_BIAS = {
    "jack":    {"feature": "jack_density",        "threshold": 0.10, "bonus": 0.15},
    "speed":   {"feature": "stream_purity",       "threshold": 0.65, "bonus": 0.15},
    "stamina": {"feature": "stamina_index",       "threshold": 0.50, "bonus": 0.10},
    "tech":    {"feature": "pattern_irregularity", "threshold": 0.10, "bonus": 0.10},
}


def _primary_role_enhanced(
    rs: dict[str, float],
    role_estimates: dict[str, dict],
    scales_data: dict,
    features: dict,
) -> str:
    """Return the dominant role using normalized MSD + confidence + structural bias."""
    role_scales = scales_data.get("scales", {})
    combined = {}
    for role in role_estimates:
        # Normalized MSD
        scale = role_scales.get(role, {})
        max_anchor = max((e.get("role_score", 1.0) for e in scale.values()), default=1.0)
        norm = rs[role] / max(max_anchor, 0.001)
        # Lookup confidence
        conf = role_estimates[role]["confidence"]
        # Base combined score
        score = norm * (0.1 + 0.9 * conf)
        # Structural bias (Tier B): boost if features confirm this role
        bias_info = _STRUCTURAL_ROLE_BIAS.get(role)
        if bias_info and features:
            feat_val = features.get(bias_info["feature"], 0.0)
            if feat_val > bias_info["threshold"]:
                score += bias_info["bonus"]
        combined[role] = score

    # Fix B: Suppress jack structural bias when a non-jack role leads by ≥6 MSD units.
    # Prevents the +0.15 jack bonus from overriding clearly stronger speed/tech/stamina signals.
    if rs:
        max_non_jack = max((rs.get(r, 0.0) for r in rs if r != "jack"), default=0.0)
        jack_score = rs.get("jack", 0.0)
        if max_non_jack > jack_score + 6.0:
            # Re-compute jack combined score WITHOUT structural bias
            scale = role_scales.get("jack", {})
            max_anchor = max((e.get("role_score", 1.0) for e in scale.values()), default=1.0)
            norm_jack = jack_score / max(max_anchor, 0.001)
            conf_jack = role_estimates.get("jack", {}).get("confidence", 0.0)
            combined["jack"] = norm_jack * (0.1 + 0.9 * conf_jack)

    # Raw MSD dominance override: trust tech/jack signal when structural biases
    # push a weaker-MSD role above a much stronger one.
    if rs and len(rs) > 1:
        combined_leader = max(combined, key=lambda r: combined[r])
        override = None
        # Case 1: tech or jack IS the global raw leader with clear margin (>=2.7)
        raw_vals = sorted(rs.values(), reverse=True)
        raw_leader = max(rs, key=lambda r: rs[r])
        if (raw_leader in ("tech", "jack")
                and raw_vals[0] - raw_vals[1] >= 2.7
                and combined_leader != raw_leader):
            override = raw_leader
        # Case 2: tech or jack loses to the SAME family (jack↔tech) but by a very
        # large raw-MSD margin (>=4.0) AND the combined winner has low lookup
        # confidence (i.e., it's in an inversion/overlap zone, not a sure call).
        if override is None and combined_leader in ("tech", "jack"):
            winner_conf = role_estimates.get(combined_leader, {}).get("confidence", 1.0)
            if winner_conf < 0.6:
                combined_winner_raw = rs.get(combined_leader, 0.0)
                for candidate in ("tech", "jack"):
                    if candidate != combined_leader and candidate in rs:
                        if rs[candidate] - combined_winner_raw >= 4.0:
                            override = candidate
                            break
        if override and override in combined:
            combined[override] = combined[combined_leader] + 0.01

    return max(combined, key=lambda r: combined[r])


# ── Specialist / Hybrid detection (Fase 5) ───────────────────────────────────

def _composite_dan(role_estimates: dict[str, dict]) -> tuple[str, str, bool]:
    """Compute composite dan with specialist/hybrid awareness.

    - Specialist (spread >= 3): primary role dominates; composite = primary dan
    - Balanced (spread <= 2): confidence-weighted average across roles
    - Generalist (spread <= 1): all roles agree
    """
    estimates = []
    for role, est in role_estimates.items():
        idx = _dan_index(est["dan"])
        estimates.append((idx, est["position"], est["confidence"], role))

    if not estimates:
        return "1st", "jack", False

    estimates.sort(key=lambda x: (x[0], x[1]))

    bottom_idx, _, _, bottom_role = estimates[0]
    top_idx = estimates[-1][0]
    spread = top_idx - bottom_idx
    is_generalist = spread <= 1

    if spread <= 2:
        # Balanced: confidence-weighted average of all roles
        total_w = sum(max(e[2], 0.05) for e in estimates)
        weighted_idx = sum((e[0] + e[1]) * max(e[2], 0.05) for e in estimates) / total_w
        composite_idx = round(weighted_idx)
    else:
        # Specialist: use the highest-confidence role, but acknowledge gap
        best = max(estimates, key=lambda e: e[2])
        composite_idx = best[0]
        # If the spread is very large (>= 5), pull down by 1 as a mild penalty
        if spread >= 5:
            composite_idx = max(0, composite_idx - 1)

    composite_dan = _DAN_ORDER[min(max(0, composite_idx), len(_DAN_ORDER) - 1)]
    return composite_dan, bottom_role, is_generalist


# ── Structural confidence modulation (Tier A) ────────────────────────────────

def _structural_confidence_mod(primary: str, features: dict) -> float:
    """Return a multiplier [0.5, 1.0] that penalizes confidence when structural
    features contradict the assigned primary role."""
    if not features:
        return 1.0

    mod = 1.0

    if primary == "jack":
        jd = features.get("jack_density", 0.0)
        if jd < 0.03:
            mod *= 0.60   # Classified jack but barely any jacks detected
        elif jd < 0.06:
            mod *= 0.80
    elif primary == "speed":
        sp = features.get("stream_purity", 0.0)
        if sp < 0.25:
            mod *= 0.70   # Classified speed but low single-note ratio
        elif sp < 0.40:
            mod *= 0.85
    elif primary == "stamina":
        si = features.get("stamina_index", 0.0)
        dur = features.get("duration_s", 0.0)
        if dur < 50:
            mod *= 0.70   # Too short for stamina classification
        elif si < 0.15:
            mod *= 0.75
    elif primary == "tech":
        pi = features.get("pattern_irregularity", 0.0)
        if pi < 0.04:
            mod *= 0.80   # Very regular patterns for a "tech" map

    return max(0.5, mod)


# ── Structural microshift (Tier B) ──────────────────────────────────────────

_MICROSHIFT_CAP = 0.5  # Maximum total microshift in dan units


def _structural_microshift(primary: str, primary_dan: str, features: dict,
                           scales_data: dict) -> float:
    """Return a small dan shift [-0.5, +0.5] based on structural features.

    Only fires for well-supported signals where structural data adds real
    discriminative power beyond what MinaCalc MSD already captures.
    """
    if not features:
        return 0.0

    shift = 0.0

    if primary == "jack":
        jd = features.get("jack_density", 0.0)
        cc = features.get("chord_complexity", 0.0)
        # Dense pure jacks: MinaCalc sometimes under-rates dense chordjack
        if jd > 0.25:
            shift += 0.25
        elif jd > 0.15 and cc < 0.10:
            shift += 0.15
        # Very sparse jacks: MinaCalc may over-rate
        if jd < 0.03:
            shift -= 0.25

    elif primary == "speed":
        sp = features.get("stream_purity", 0.0)
        dcv = features.get("density_cv", 0.0)
        # Pure high stream_purity confirms speed difficulty
        if sp > 0.80:
            shift += 0.15
        # High density variance = inconsistent density, not pure stream
        if dcv > 0.50:
            shift -= 0.20

    elif primary == "stamina":
        si = features.get("stamina_index", 0.0)
        dur = features.get("duration_s", 0.0)
        # High sustained effort index
        if si > 0.70:
            shift += 0.20
        # Short maps shouldn't be rated as high stamina
        if dur < 60:
            shift -= 0.30
        elif dur < 90:
            shift -= 0.10

    elif primary == "tech":
        pi = features.get("pattern_irregularity", 0.0)
        tv = features.get("transition_var", 0.0)
        # High pattern irregularity confirms tech difficulty
        if pi > 0.15:
            shift += 0.15
        # Complex column transitions
        if tv > 0.65:
            shift += 0.10

    return max(-_MICROSHIFT_CAP, min(_MICROSHIFT_CAP, shift))


# ── Jack dominance correction (ported from legacy_signals.py, Fase 6) ────────

_JACK_DOM_THRESHOLD = 0.55
_JACK_DOM_MAX_SHIFT = 0.25
_JACK_DOM_SCALE = 0.45


def _jack_dominance_shift(features: dict) -> float:
    """Additional shift for jack-dominant charts that MinaCalc under-rates.

    Adapted from Block E2 strain.py: uses jack_ratio as dominance proxy
    and density_cv as variance proxy.
    """
    if not features:
        return 0.0
    jr = features.get("jack_ratio", 0.0)
    if jr < _JACK_DOM_THRESHOLD:
        return 0.0
    dcv = min(1.0, features.get("density_cv", 0.0))
    return min(_JACK_DOM_MAX_SHIFT, dcv * _JACK_DOM_SCALE * jr)


# ── Position / dan clamping ──────────────────────────────────────────────────

def _apply_shift(dan: str, position: float, shift: float) -> tuple[str, float]:
    """Apply a fractional dan shift to (dan, position), clamping to valid range."""
    idx = _dan_index(dan)
    effective = idx + position + shift
    new_idx = int(effective)
    new_pos = effective - new_idx
    new_idx = max(0, min(len(_DAN_ORDER) - 1, new_idx))
    new_pos = max(0.0, min(0.99, new_pos))
    return _DAN_ORDER[new_idx], round(new_pos, 3)


# ── Explanation builder (Fase 7) ─────────────────────────────────────────────

def _build_explanation(
    primary: str,
    primary_dan: str,
    features: dict,
    microshift: float,
    role_estimates: dict,
    agreement_conf: float,
) -> str:
    """Build a human-readable explanation of the dan assignment."""
    parts = []

    # Primary role
    role_label = {"jack": "Jack", "speed": "Speed", "tech": "Tech", "stamina": "Stamina"}
    parts.append(f"{primary_dan} by {role_label.get(primary, primary)} dominance")

    # Structural characterization (Tier C)
    if features:
        tags = []
        sp = features.get("stream_purity", 0.0)
        jd = features.get("jack_density", 0.0)
        pi = features.get("pattern_irregularity", 0.0)
        si = features.get("stamina_index", 0.0)
        cc = features.get("chord_complexity", 0.0)
        dcv = features.get("density_cv", 0.0)
        dur = features.get("duration_s", 0.0)

        if sp > 0.75:
            tags.append("high stream purity")
        if jd > 0.15:
            tags.append("dense jacks")
        elif jd > 0.08:
            tags.append("moderate jacks")
        if pi > 0.15:
            tags.append("irregular patterns")
        if si > 0.60:
            tags.append("sustained density")
        if cc > 0.30:
            tags.append("complex chords")
        if dcv > 0.50:
            tags.append("variable density")
        if dur > 180:
            tags.append("long map")

        if tags:
            parts.append("; ".join(tags))

    # Microshift
    if abs(microshift) > 0.05:
        direction = "up" if microshift > 0 else "down"
        parts.append(f"structural shift {direction} ({microshift:+.2f})")

    # Confidence context
    if agreement_conf < 0.5:
        # Find the most disagreeing role
        if role_estimates:
            primary_idx = _dan_index(primary_dan)
            worst = max(
                role_estimates.items(),
                key=lambda kv: abs(_dan_index(kv[1]["dan"]) - primary_idx)
            )
            parts.append(f"low agreement ({worst[0]} at {worst[1]['dan']})")

    return " · ".join(parts)


def _derive_family(primary: str) -> str:
    """Map the primary role to a family label for the overlay."""
    mapping = {"jack": "jack", "tech": "tech", "speed": "stream", "stamina": "stamina"}
    return mapping.get(primary, "hybrid")


# ── Core estimator ────────────────────────────────────────────────────────────

def estimate(osu_path: str, rate: float = 1.0, *, features: dict | None = None) -> dict | None:
    """Estimate the Reform dan for *osu_path* using role-based MSD lookup
    with structural feature modulation.

    Returns None if prerequisites are missing (no CLI, no scales, non-4K).

    When *features* is supplied by the caller, the redundant .osu parse
    inside ``_extract_structural`` is skipped.
    """
    scales_data = _load_scales()
    if scales_data is None:
        return None

    scores = minacalc_calc(osu_path, rate=rate, goal=0.93, mode="msd")
    if scores is None:
        return None

    duration_s = float(scores.get("duration_s", 0))
    warnings: list[str] = []

    if duration_s < 30:
        warnings.append(f"very_short_map_{int(duration_s)}s")

    # ── Structural features (reuse caller's if available) ──────────
    if features is None:
        features = _extract_structural(osu_path)
    if not features:
        warnings.append("structural_features_unavailable")

    # ── Compute role scores ────────────────────────────────────────
    rs = _role_scores(scores)

    # ── Per-role dan lookup (band-based) ───────────────────────────
    thresholds = scales_data.get("thresholds", {})
    role_estimates: dict[str, dict] = {}

    for role in _ROLES:
        role_thresh = thresholds.get(role, {})
        if not role_thresh:
            continue
        dan, position, confidence = _lookup_role_dan(rs[role], role_thresh)
        role_estimates[role] = {
            "dan": dan,
            "dan_label": _DAN_LABELS.get(dan, dan),
            "position": position,
            "sublevel": _sublevel(position),
            "confidence": confidence,
            "msd": round(rs[role], 2),
        }

    if not role_estimates:
        return None

    # ── Primary role (structural-enhanced) ─────────────────────────
    primary = _primary_role_enhanced(rs, role_estimates, scales_data, features)
    primary_est = role_estimates[primary]
    primary_dan = primary_est["dan"]
    primary_position = primary_est["position"]

    # ── Structural microshift (Tier B) ─────────────────────────────
    microshift = _structural_microshift(primary, primary_dan, features, scales_data)
    # Add jack dominance correction (legacy gate, Fase 6)
    if primary == "jack":
        microshift += _jack_dominance_shift(features)
        microshift = max(-_MICROSHIFT_CAP, min(_MICROSHIFT_CAP, microshift))

    # Apply shift
    adjusted_dan, adjusted_position = _apply_shift(
        primary_dan, primary_position, microshift
    )

    # ── Composite (specialist/hybrid aware) ────────────────────────
    composite_dan, bottleneck_role, is_generalist = _composite_dan(role_estimates)

    # ── Fix A: Composite rescue (8th-dan corpus outliers only) ─────
    # Rescues maps where all roles average to 8th but the primary role
    # scores low enough to drag the prediction to 5th or 6th.  The
    # condition is intentionally tight (composite == exactly 8th AND
    # adjusted <= 6th) to avoid spurious upgrades on higher-tier maps
    # whose composite diverges due to overlapping scales.
    primary_conf_raw = role_estimates[primary]["confidence"]
    composite_idx_raw = _dan_index(composite_dan)
    adjusted_idx_raw = _dan_index(adjusted_dan)
    _use_composite = (
        primary_conf_raw < 0.5              # primary is uncertain
        and composite_idx_raw == 7          # composite says exactly 8th dan
        and adjusted_idx_raw <= 5           # adjusted says only 5th or 6th
    )
    final_dan = composite_dan if _use_composite else adjusted_dan
    final_position = 0.5 if _use_composite else adjusted_position

    # ── Confidence: inter-role agreement × structural modulation ───
    primary_idx = _dan_index(final_dan)
    agreeing = sum(
        1 for e in role_estimates.values()
        if abs(_dan_index(e["dan"]) - primary_idx) <= 1
    )
    agreement_confidence = agreeing / max(len(role_estimates), 1)
    struct_conf_mod = _structural_confidence_mod(primary, features)
    final_confidence = round(agreement_confidence * struct_conf_mod, 3)

    # ── Role breakdown text ────────────────────────────────────────
    role_breakdown_text = " · ".join(
        f"{role[0].upper()}:{_DAN_SHORT.get(role_estimates[role]['dan'], role_estimates[role]['dan'])}"
        for role in _ROLES
        if role in role_estimates
    )

    # ── Explanation (Tier C) ───────────────────────────────────────
    explanation = _build_explanation(
        primary, final_dan, features, microshift,
        role_estimates, agreement_confidence,
    )

    # ── Family from dominant role ──────────────────────────────────
    family = _derive_family(primary)

    # ── DP approximation ───────────────────────────────────────────
    dan_idx = _dan_index(final_dan)
    dp_approx = round(1.0 + dan_idx + final_position, 2)

    return {
        # ── Core fields ────────────────────────────────────────────
        "dp":              dp_approx,
        "dan_label":       _DAN_LABELS.get(final_dan, final_dan),
        "dan_short":       final_dan,
        "sublevel":        _sublevel(final_position),
        "confidence":      final_confidence,
        "family":          family,
        "corrections":     [],
        # ── Role-based fields ──────────────────────────────────────
        "primary_dan":          final_dan,
        "primary_role":         primary,
        "role_estimates":       role_estimates,
        "composite_dan":        composite_dan,
        "bottleneck_role":      bottleneck_role,
        "is_generalist":        is_generalist,
        "role_breakdown_text":  role_breakdown_text,
        # ── Structural fields ──────────────────────────────────────
        "structural_shift":     round(microshift, 3),
        "structural_conf_mod":  round(struct_conf_mod, 3),
        "explanation":          explanation,
        "features":             features if features else None,
        # ── Raw MinaCalc data ──────────────────────────────────────
        "skillsets":       {k: round(scores.get(k, 0.0), 2)
                            for k in ["stream", "jumpstream", "handstream",
                                      "stamina", "jackspeed", "chordjack",
                                      "technical"]
                            if k in scores},
        "overall_msd":     round(scores.get("overall", 0.0), 2),
        "role_scores":     {r: round(v, 2) for r, v in rs.items()},
        "duration_s":      duration_s,
        "note_count":      scores.get("note_count", 0),
        "warnings":        warnings,
        "engine":          "minacalc_roles_v2",
    }
